[[redirects]]
  from = "https://brishack.io/*"
  to = "https://2024.brishack.io/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://www.brishack.io/*"
  to = "https://2024.brishack.io/:splat"
  status = 302
  force = true
  
  [[redirects]]
  from = "http://brishack.io/*"
  to = "https://2024.brishack.io/:splat"
  status = 302
  force = true

[[redirects]]
  from = "http://www.brishack.io/*"
  to = "https://2024.brishack.io/:splat"
  status = 302
  force = true
